devices/urls.py
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from .views import (
    DeviceConfigurationUpdateView,
    DeviceConfigurationViewSet,
    DeviceCreateView,
    DeviceDetailView,
    DeviceListView,
    DeviceLocationListAPIView,
    DeviceRecordingsAPIView,
    DeviceUpdateView,
    LocationCreateView,
    LocationMetricsViewSet,
    LocationRecordingsViewSet,
    LocationUpdateView,
    UptimeAPIView,
)

router = SimpleRouter()
router.register("config", DeviceConfigurationViewSet)
router.register("location_metrics", LocationMetricsViewSet)
router.register("location_recordings", LocationRecordingsViewSet)

urlpatterns = [
    path("", DeviceListView.as_view(), name="device_list"),
    path("locations/", DeviceLocationListAPIView.as_view(), name="device_locations"),
    path("<uuid:pk>", DeviceDetailView.as_view(), name="device_detail"),
    path("create_device/", DeviceCreateView.as_view(), name="create_device"),
    path("<uuid:pk>/edit/", DeviceUpdateView.as_view(), name="edit_device"),
    path(
        "<uuid:pk>/config_edit",
        DeviceConfigurationUpdateView.as_view(),
        name="edit_config",
    ),
    path("create_location", LocationCreateView.as_view(), name="create_location"),
    path("<uuid:pk>/edit_location", LocationUpdateView.as_view(), name="edit_location"),
    path("uptime/<str:device_id>", UptimeAPIView.as_view(), name="uptime_info"),
    path(
        "device/<uuid:pk>/recordings/",
        DeviceRecordingsAPIView.as_view(),
        name="device_recordings_api",
    ),
    path("", include(router.urls)),
]

noise_dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    # Django admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("django.contrib.auth.urls")),
    # Local apps
    path("accounts/", include("users.urls")),
    path("", include("pages.urls")),
    path("devices/", include("devices.urls")),
    path("audio/", include("recordings.urls")),
    path("device_metrics/", include("device_metrics.urls")),
    path("analysis/", include("analysis.urls")),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="docs"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

devices/models.py
import calendar
import uuid
from datetime import datetime, timedelta

import pytz
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from taggit.models import GenericUUIDTaggedItemBase, TaggedItemBase

from noise_dashboard.settings import TIME_ZONE


class UUIDTaggedItem(GenericUUIDTaggedItemBase, TaggedItemBase):
    class Meta:
        verbose_name = _("Tag")
        verbose_name_plural = _("Tags")


class Device(models.Model):
    class ProductionStage(models.TextChoices):
        DEPLOYED = "Deployed", _("Deployed")
        TESTING = "Testing", _("Testing")
        SHELVED = "Shelved", _("Shelved")
        MAINTENANCE = "Maintenance", _("Maintenance")
        RETIRED = "Retired", _("Retired")

    class Configured(models.IntegerChoices):
        CONFIGURED = (1, _("Configured"))
        NOT_CONFIGURED = (0, _("Not Configured"))

    class Mode(models.IntegerChoices):
        AUTO_MODE = (1, _("Auto"))
        MANUAL_MODE = (2, _("Manual"))

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    device_id = models.CharField(max_length=200, unique=True)
    imei = models.CharField(max_length=15)
    device_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10)
    version_number = models.CharField(max_length=10)
    production_stage = models.CharField(
        max_length=50, choices=ProductionStage.choices, default=ProductionStage.TESTING
    )
    tags = TaggableManager(through=UUIDTaggedItem)
    metrics_url = models.URLField(max_length=255, default="http://localhost:3000/")

    # Configuration fields
    configured = models.IntegerField(
        choices=Configured.choices, default=Configured.NOT_CONFIGURED
    )
    mode = models.IntegerField(choices=Mode.choices, default=Mode.AUTO_MODE)
    dbLevel = models.IntegerField(default=50)
    recLength = models.IntegerField(default=10)
    recInterval = models.IntegerField(default=10)
    uploadAddr = models.CharField(
        default="http://localhost:8000/audio/", max_length=100
    )

    @property
    def lastseen(self):
        """
        Return the last seen time of the device. It prioritizes the following in order:
        1. Last metric text file uploaded time
        2. Last device metrics uploaded time
        3. Last recording uploaded time
        """
        # Fetch the last metric text file upload time
        last_metric_file = self.get_last_metric_text_file()

        # Fetch the last device metrics upload time
        last_device_metric = self.get_metrics.first()

        # Fetch the last recording uploaded time
        last_recording = self.get_recordings.first()

        # Compare and return the most recent time from all three sources
        timestamps = [
            last_metric_file.time_uploaded if last_metric_file else None,
            last_device_metric.time_uploaded if last_device_metric else None,
            last_recording.time_uploaded if last_recording else None
        ]

        # Filter out None values and return the latest timestamp
        valid_timestamps = [time for time in timestamps if time is not None]
        return max(valid_timestamps, default=None)

    def get_last_metric_text_file(self):
        try:
            # Retrieve the last metricstextfile uploaded for this device
            return self.metricstextfile_set.order_by("-time_uploaded").first()
        except self.metricstextfile_set.model.DoesNotExist:
            # Handle the case where there are no metricstextfiles
            return None

    def __str__(self):
        return self.device_id

    @property
    def get_recordings(self):
        return self.recording_set.order_by("-time_recorded")[:10]

    @property
    def get_metrics(self):
        return self.devicemetrics_set.order_by("-time_uploaded")[:10]

    @property
    def get_metric_files(self):
        return self.metricstextfile_set.order_by("-time_uploaded")[:20]

    def get_absolute_url(self):
        return reverse("device_detail", args=[str(self.id)])

    @property
    def uptime(self):
        """
        Calculate and return the uptime of the device.
        """
        return self.calculate_uptime(False)

    timezone = pytz.timezone(TIME_ZONE)

    def calculate_uptime(self, audio=True):
        """
        Returns gaps between upload times and total uptime. Returns a dictionary with:
        upload_gaps: Long gaps between uploads (1.5 hours or more)
        uptime: Number of hours/days since there was a 24-hour upload gap.
        """

        big_gaps = []
        went_online = None
        previous_downtime = None

        now = datetime.now(self.timezone)
        delta = timedelta(weeks=4)
        start_time = now - delta
        uploaded_times = self.get_uploaded_times(audio, now, start_time)
        uptime_percentages = self.calculate_monthly_uptime(uploaded_times)
        months = self.get_next_12_months()

        if not uploaded_times:
            return {
                "upload_gaps": [],
                "upload_gaps_len": 0,
                "uptime": 0,
                "previous_downtime": None,
                "uptime_percentages": [],
            }

        for date_from, date_to in zip(uploaded_times[:-1], uploaded_times[1:]):
            gap_time = date_to - date_from
            gap = round(gap_time.total_seconds() / 3600, 2)

            formatted_date_from = date_from.strftime("%Y-%m-%d %H:%M")
            formatted_date_to = date_to.strftime("%Y-%m-%d %H:%M")

            if gap > 3.0:
                big_gaps.append(
                    (gap, f"From {formatted_date_from} to {formatted_date_to}")
                )

            if gap >= 24 and not went_online:
                went_online = date_to
                previous_downtime = f"From {formatted_date_from} to {formatted_date_to}"

        if not went_online:
            went_online = start_time

        def_time = now - went_online
        uptime = round(max(0, def_time.total_seconds() / 3600), 2)

        return {
            "upload_gaps": big_gaps,
            "upload_gaps_len": len(big_gaps),
            "uptime": uptime,
            "previous_downtime": previous_downtime,
            "uptime_percentages": zip(months, uptime_percentages),
        }

    def get_uploaded_times(self, audio, now, start_time):
        query_set = self.recording_set if audio else self.metricstextfile_set

        try:
            files_dates = (
                query_set.filter(time_uploaded__range=[start_time, now])
                .values_list("time_uploaded", flat=True)
                .order_by("time_uploaded")
            )
            return list(files_dates)
        except query_set.model.DoesNotExist:
            # Handle the case where there are no metricstextfiles
            return []

    def get_next_12_months(self):
        current_month = datetime.now().replace(
            day=1
        )  # Get the first day of the current month
        months = [current_month]

        for _ in range(11):
            current_month = current_month + timedelta(
                days=31
            )  # Add an arbitrary number of days to move to the next month
            current_month = current_month.replace(
                day=1
            )  # Set the day to 1 to get the first day of the month
            months.append(current_month)

        return months

    def calculate_monthly_uptime(self, uploaded_times):
        current_month = datetime.now().month
        uptime_per_month = [0] * 12

        for upload_time in uploaded_times:
            month = upload_time.month - 1  # Adjust to 0-indexed
            uptime_per_month[month] += 1

        total_months = len(uptime_per_month)
        current_month_index = (current_month - 1) % total_months

        # Calculate uptime percentages
        uptime_percentages = [
            (count / (days * 24)) * 100
            for count, days in zip(
                uptime_per_month,
                [calendar.monthrange(2024, i)[1] for i in range(1, 13)],
            )
        ]

        # Shift the list so that the current month is at the beginning
        uptime_percentages = (
            uptime_percentages[current_month_index:]
            + uptime_percentages[:current_month_index]
        )

        return uptime_percentages

    def filter_time_by_month_and_year(self, time_formats, month, year):
        # Create an empty list to store the filtered time formats
        filtered_time_formats = []
        # Loop through each time format in the list
        for time_format in time_formats:
            # Parse the time format into a datetime object using the isoformat method
            datetime_object = datetime.datetime.fromisoformat(time_format)
            # Check if the month and year attributes of the datetime object match the given month and year
            if datetime_object.month == month and datetime_object.year == year:
                # If yes, append the time format to the filtered list
                filtered_time_formats.append(time_format)
        # Return the filtered list
        return filtered_time_formats

    def calculate_uptime_percentage(self, duration_weeks=4):
        """
        Calculate and return the uptime percentage of the device for a given duration.
        """
        now = datetime.now(self.timezone)
        delta = timedelta(weeks=duration_weeks)
        start_time = now - delta
        uptime_data = self.calculate_uptime(False)

        total_hours_in_duration = duration_weeks * 7 * 24
        return round((uptime_data["uptime"] / total_hours_in_duration) * 100, 2)


location_category_information = {
    "A": {
        "description": "Category A: hospital, convalescence home, sanatorium, home for the aged and "
        "higher learning institute, conference rooms, public library, "
        "environmental or recreational sites",

devices/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView
from rest_framework import viewsets
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from recordings.models import Recording

from .forms import DeviceConfigurationForm, DeviceForm
from .models import Device, Location
from .serializers import (
    DeviceConfigSerializer,
    DeviceLocationSerializer,
    LocationMetricsSerializer,
    LocationRecordingsSerializer,
    RecordingSerializer,
)
from .uptime_calculation import calculate_uptime


class DeviceLocationListAPIView(ListAPIView):
    queryset = Location.objects.all()
    serializer_class = DeviceLocationSerializer


class DeviceListView(LoginRequiredMixin, ListView):
    model = Device
    context_object_name = "device_list"
    template_name = "devices/device_list.html"


class LocationMetricsViewSet(viewsets.ModelViewSet):
    serializer_class = LocationMetricsSerializer
    queryset = Location.objects.all()
    lookup_field = "device"


class LocationRecordingsViewSet(viewsets.ModelViewSet):
    serializer_class = LocationRecordingsSerializer
    queryset = Location.objects.all()
    lookup_field = "id"


class DeviceDetailView(LoginRequiredMixin, DetailView):
    model = Device
    context_object_name = "device"
    template_name = "devices/device_detail.html"


class DeviceCreateView(LoginRequiredMixin, CreateView):
    model = Device
    form_class = DeviceForm
    success_url = "/devices/"
    template_name = "devices/create_device.html"


class DeviceUpdateView(LoginRequiredMixin, UpdateView):
    model = Device
    form_class = DeviceForm
    success_url = "/devices/"
    template_name = "devices/edit_device.html"


class LocationCreateView(LoginRequiredMixin, CreateView):
    model = Location
    fields = "__all__"
    success_url = "/devices/"
    template_name = "devices/update_location.html"


class LocationUpdateView(LoginRequiredMixin, UpdateView):
    model = Location
    fields = [
        "latitude",
        "longitude",
        "city",
        "division",
        "parish",
        "village",
        "category",
    ]
    success_url = "/devices/"
    template_name = "devices/update_location.html"


class DeviceConfigurationUpdateView(LoginRequiredMixin, UpdateView):
    model = Device
    form_class = DeviceConfigurationForm
    template_name = "devices/edit_configuration.html"

    def get_success_url(self):
        return reverse("device_detail", kwargs={"pk": self.object.pk})


class DeviceConfigurationViewSet(viewsets.ModelViewSet):
    serializer_class = DeviceConfigSerializer
    queryset = Device.objects.all()
    lookup_field = "imei"


class UptimeAPIView(APIView):
    def get(self, request, *args, **kwargs):
        device_id = self.kwargs["device_id"]
        past_weeks = int(request.query_params.get("past_weeks", 4))

        # Assuming you have a Device model, fetch the device object
        device = get_object_or_404(Device, device_id=device_id)

        # Call the calculate_uptime function with the device object
        uptime_based_on_audio_uploads = calculate_uptime(device, past_weeks, audio=True)
        uptime_based_on_metrics_uploads = calculate_uptime(
            device, past_weeks, audio=False
        )

        context = {
            "device": device,  # Add the device to the context if needed in the template
            "uptime_based_on_audio_uploads": uptime_based_on_audio_uploads,
            "uptime_based_on_metrics_uploads": uptime_based_on_metrics_uploads,
        }

        return TemplateResponse(request, "devices/device_detail.html", context)


class DeviceRecordingsAPIView(APIView):
    def get(self, request, pk):
        try:
            device = Device.objects.get(pk=pk)
            recordings = device.get_recordings
            # Assuming you have a serializer for Recording model
            serializer = RecordingSerializer(recordings, many=True)
            return Response(serializer.data, status=200)
        except Device.DoesNotExist:
            return Response({"error": "Device not found"}, status=404)

templates/devices/create_device.html
{% extends '_base.html' %}

{% load crispy_forms_filters %}

{% block title %}Create Device{% endblock title %}

{% block content %}
    {% include "sidebar.html" %}
    <div class="content-container">
        <div class="container-fluid">
            {% include "navbar.html" %}
            <div class="mt-4 mx-3">
                <h4 class="my-3">Create New Device</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary mt-2" type="submit">Create Device</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/devices/create_location.html
{% extends '_base.html' %}

{% load crispy_forms_filters %}

{% block title %}Update Device Location{% endblock title %}

{% block content %}
    {% include "sidebar.html" %}
    <div class="content-container">
        <div class="container-fluid">
            {% include "navbar.html" %}
            <div class="mt-4 mx-3">
                <h4 class="my-3">Update Device Location</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary mt-2" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/devices/device_detail.html
{% extends '_base.html' %}

{% load crispy_forms_filters %}

{% block title %}{{ device.device_id }}{% endblock title %}

{% block content %}
{% include "sidebar.html" %}
<div class="content-container">
    <div class="container-fluid">
        {% include "navbar.html" %}
        <div class="card-group m-3">
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h4>{{ device.device_id }} Details</h4>
                    </div>
                    <p><strong>Device ID</strong>: {{ device.device_id }}</p>
                    <p><strong>Device Name</strong>: {{ device.device_name }}</p>
                    <p><strong>IMEI Number</strong>: {{ device.imei }}</p>
                    <p><strong>Phone Number</strong>: {{ device.phone_number }}</p>
                    <p><strong>Version Number</strong>: {{ device.version_number }}</p>
                    <p><strong>Production Stage</strong>: {{ device.production_stage }}</p>
                    <p><strong>Device Last Seen:</strong>
                        <span class="btn btn-light btn-outline-secondary btn-sm">{{ device.lastseen|default:"N/A"  }}</span>
                    </p>
                    <p><strong>Tags:</strong>
                        {% for tag in device.tags.all %}
                        <span class="btn btn-light btn-outline-secondary btn-sm">{{ tag }}</span>
                        {% endfor %}
                    </p>
                    <p><strong>Location:</strong></p>
                    {% if device.location %}
                    <p class="ml-3">
                        <strong>City</strong>: {{ device.location.city }},
                        <strong>Division</strong>: {{ device.location.division }}
                        <strong>Parish/Ward</strong>: {{ device.location.parish }},
                        <strong>Village/Sub-Ward</strong>: {{ device.location.village }}
                        <strong>Location Category: </strong> {{ device.location.location_description }}
                    </p>
                    {% else %}
                    <p class="ml-3">N/A</p>
                    {% endif %}
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="card-title">
                        <h4>{{ device.device_id }} Configuration</h4>
                    </div>
                    <p><strong>Configured/Enabled</strong>: {{ device.get_configured_display }}</p>
                    <p><strong>Mode</strong>: {{ device.get_mode_display }}</p>
                    <p><strong>DB Level</strong>: {{ device.dbLevel }}</p>
                    <p><strong>Recording Length</strong>: {{ device.recLength }}</p>
                    <p><strong>Recording Interval</strong>: {{ device.recInterval }}</p>
                    <p><strong>Upload Address</strong>: {{ device.uploadAddr }}</p>
                </div>
            </div>
        </div>
       <!-- Add this section to display uptime information -->
        <div class="card m-3">
            <div class="card-body">
                <div class="card-title">
                    <h3>Device Uptime</h3>
                </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: {{ device.calculate_uptime_percentage }}%;" aria-valuenow="{{ device.calculate_uptime_percentage }}" aria-valuemin="0" aria-valuemax="100">{{ device.calculate_uptime_percentage }}%</div>
            </div>
            <p>The device has been online for {{ device.uptime.uptime | default:"0" }} hours since the last 24-hour gap.</p>
            <h3>Upload Gaps</h3>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">Gap Duration (hours)</th>
                  <th scope="col">Gap Period</th>
                </tr>
              </thead>
              <tbody>
                {% for gap, period in device.uptime.upload_gaps %}
                <tr>
                  <td>{{ gap }}</td>
                  <td>{{ period }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            <!-- <table>
                <tr>
                  <th>Month</th>
                  <th>Uptime Percentage</th>
                </tr>
                {% for month, percentage in device.uptime.uptime_percentages %}
                <tr>
                  <td>{{ month }}</td>
                  <td>{{ percentage }}%</td>
                </tr>
                {% endfor %}
              </table> -->
              
            <p>The device had {{ device.uptime.upload_gaps_len | default:"0" }} long gaps between uploads in the past 4 weeks.</p>
            <h3>Previous Downtime</h3>
            <p>The device was offline {{ device.uptime.previous_downtime }}.</p>
          </div>
        </div>
          
        <!-- End of uptime information section -->
        <a href="{% url 'edit_device' device.id %}" class="btn btn-primary mx-3 my-1">Edit Device</a>
        <a href="{% url 'edit_config' device.id %}" class="btn btn-primary mx-3 my-1">Edit
            Configuration</a>
        {% if device.location %}
        <a href="{% url 'edit_location' device.location.id %}" class="btn btn-primary mx-3 my-1">Edit
            Location</a>
        {% else %}
        <a href="{% url 'create_location' %}" class="btn btn-primary mx-3 my-1">Add Location</a>
        {% endif %}
        <a href="{{ device.metrics_url }}" class="btn btn-primary mx-3 my-1  pull-right" target="_blank">View
            Metrics</a>
        <div class="card m-3">
            <div class="card-body">
                <div class="card-title">
                    <h4>{{ device.device_id }} Recordings (Latest 10 or less)</h4>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Recording Directory</th>
                            <th scope="col">Time Recorded</th>
                            <th scope="col">Time Uploaded</th>
                            <th scope="col">Triggering Threshold</th>
                            <th scope="col">Audio</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for recording in device.get_recordings %}
                        <tr>
                            <td>{{ recording.audio }}</td>
                            <td>
                                {{ recording.time_recorded }}
                            </td>
                            <td>{{ recording.time_uploaded }}</td>
                            <td>{{ recording.triggering_threshold }}</td>
                            <td>
                                <audio controls class="audio-player">
                                    <source src="{{ recording.audio_url }}" type="audio/wav">
                                    Your browser does not support the audio element.
                                </audio>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card m-3">
            <div class="card-body">
                <div class="card-title">
                    <h4>Metric Files</h4>
                </div>
                {% for metric_file in device.get_metric_files %}
                <ul><a href="{{ metric_file.text_file_url }}" target="_blank">{{ metric_file.filename }}</a> upload at
                    {{ metric_file.time_uploaded }}</ul>
                {% endfor %}
                {# <table class="table table-hover">#}
                    {# <thead>#}
                        {# <tr>#}
                            {# <th scope="col">Signal strength</th>#}
                            {# <th scope="col">DB Level</th>#}
                            {# <th scope="col">Average DB Level</th>#}
                            {# <th scope="col">Max DB Level</th>#}
                            {# <th scope="col">No. of Exceedances</th>#}
                            {# <th scope="col">Last Recorded</th>#}
                            {# <th scope="col">Last Uploaded</th>#}
                            {# <th scope="col">Panel Voltage</th>#}
                            {# <th scope="col">Battery Voltage</th>#}
                            {# <th scope="col">Data Balance</th>#}
                            {# <th scope="col">Time Uploaded</th>#}
                            {# </tr>#}
                        {# </thead>#}
                    {# <tbody>#}
                        {# {% for metric in device.get_metrics %}#}
                        {# <tr>#}
                            {# <td>{{ metric.sig_strength }}</td>#}
                            {# <td>{{ metric.db_level }}</td>#}
                            {# <td>{{ metric.avg_db_level }}</td>#}
                            {# <td>{{ metric.max_db_level }}</td>#}
                            {# <td>{{ metric.no_of_exceedances}}</td>#}
                            {# <td>{{ metric.last_rec }}</td>#}
                            {# <td>{{ metric.last_upl }}</td>#}
                            {# <td>{{ metric.panel_voltage }}</td>#}
                            {# <td>{{ metric.battery_voltage }}</td>#}
                            {# <td>{{ metric.data_balance }}</td>#}
                            {# <td>{{ metric.time_uploaded }}</td>#}
                            {# </tr>#}
                        {# {% endfor %}#}
                        {# </tbody>#}
                    {# </table>#}
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var audios = document.querySelectorAll('.audio-player');
        audios.forEach(function(audio) {
            audio.addEventListener('play', function() {
                audios.forEach(function(otherAudio) {
                    if (otherAudio !== audio) {
                        otherAudio.pause();
                    }
                });
            }, false);
        });
    });
    </script>
{% endblock content %}

templates/devices/device_list.html
{% extends '_base.html' %}

{% block title %}Devices{% endblock title %}

{% block content %}
{% include "sidebar.html" %}
<div class="content-container">
  <div class="container-fluid">
    {% include "navbar.html" %}
    <a href="{% url 'create_device' %}" class="btn btn-primary m-3">Add New Device</a>
    <a href="{% url 'create_location' %}" class="btn btn-primary m-3">Add Location to Devices</a>
    <div class="row">
        <div class="col mb-4 mb-lg-0 ml-3 mr-3">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">DEVICE ID</th>
                      <th scope="col">IMEI NUMBER</th>
                      <th scope="col">DEVICE NAME</th>
                      <th scope="col">PHONE NUMBER</th>
                      <th scope="col">VERSION NUMBER</th>
                      <th scope="col">PRODUCTION STAGE</th>
                      <th scope="col">LAST SEEN</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for device in device_list %}
                    <tr>
                      <td>
                        <a href="{{ device.get_absolute_url }}">{{ device.device_id }}</a>
                      </td>
                      <td>{{ device.imei }}</td>
                      <td>{{ device.device_name }}</td>
                      <td>{{ device.phone_number }}</td>
                      <td>{{ device.version_number }}</td>
                      <td>{{ device.production_stage }}</td>
                      <td>{{ device.lastseen|default:"N/A"  }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
{% endblock content %}

templates/devices/edit_configuration.html
{% extends '_base.html' %}

{% load crispy_forms_filters %}

{% block title %}Edit Device Configuration{% endblock title %}

{% block content %}
    {% include "sidebar.html" %}
    <div class="content-container">
        <div class="container-fluid">
            {% include "navbar.html" %}
            <div class="mt-4 mx-3">
                <h4 class="my-3">Edit Device Configuration</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button class="btn btn-primary mt-2" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}